/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LazyEmbed {
        /**
          * Alternative text for the preview image
         */
        "alt": string;
        /**
          * Aspect ratio used when height is "auto" (e.g. "16:9", "4:3", "1:1")
         */
        "aspectRatio": string;
        /**
          * Whether the embedded video should autoplay once loaded. Note: browsers may still block autoplay if the video has sound.
         */
        "autoplay": boolean;
        /**
          * Explicit height of the embed. When left as "auto", the embed is sized by the aspectRatio prop instead.
         */
        "height": string;
        /**
          * CSS selector for elements that should trigger video loading when clicked
         */
        "loadOnClickSelector": string;
        /**
          * CSS selector for a parent element that triggers loading when it becomes visible
         */
        "loadOnParentOpen": string;
        /**
          * Load only the preview image when the component becomes visible in the viewport
         */
        "loadOnVisible": boolean;
        /**
          * Load the video by replacing the preview image with the embed iframe
         */
        "loadVideo": () => Promise<void>;
        /**
          * Extra query parameters to append to the embed URL (e.g. "start=30&loop=1")
         */
        "params": string;
        /**
          * Load the video when it becomes visible in the viewport, without user interaction
         */
        "playOnVisible": boolean;
        /**
          * URL of the preview image to display before loading the video. When omitted, a YouTube thumbnail is derived automatically for YouTube videos.
         */
        "previewImage": string;
        /**
          * URL of the video to embed (YouTube, Vimeo, or any other iframe URL)
         */
        "src": string;
        /**
          * Title of the video (used for the iframe title, for accessibility)
         */
        "videoTitle": string;
        /**
          * Width of the embed (can be px or %)
         */
        "width": string;
        /**
          * Load YouTube videos via youtube-nocookie.com (enhanced privacy mode)
         */
        "youtubeNocookie": boolean;
    }
}
declare global {
    interface HTMLLazyEmbedElement extends Components.LazyEmbed, HTMLStencilElement {
    }
    var HTMLLazyEmbedElement: {
        prototype: HTMLLazyEmbedElement;
        new (): HTMLLazyEmbedElement;
    };
    interface HTMLElementTagNameMap {
        "lazy-embed": HTMLLazyEmbedElement;
    }
}
declare namespace LocalJSX {
    interface LazyEmbed {
        /**
          * Alternative text for the preview image
         */
        "alt"?: string;
        /**
          * Aspect ratio used when height is "auto" (e.g. "16:9", "4:3", "1:1")
         */
        "aspectRatio"?: string;
        /**
          * Whether the embedded video should autoplay once loaded. Note: browsers may still block autoplay if the video has sound.
         */
        "autoplay"?: boolean;
        /**
          * Explicit height of the embed. When left as "auto", the embed is sized by the aspectRatio prop instead.
         */
        "height"?: string;
        /**
          * CSS selector for elements that should trigger video loading when clicked
         */
        "loadOnClickSelector"?: string;
        /**
          * CSS selector for a parent element that triggers loading when it becomes visible
         */
        "loadOnParentOpen"?: string;
        /**
          * Load only the preview image when the component becomes visible in the viewport
         */
        "loadOnVisible"?: boolean;
        /**
          * Extra query parameters to append to the embed URL (e.g. "start=30&loop=1")
         */
        "params"?: string;
        /**
          * Load the video when it becomes visible in the viewport, without user interaction
         */
        "playOnVisible"?: boolean;
        /**
          * URL of the preview image to display before loading the video. When omitted, a YouTube thumbnail is derived automatically for YouTube videos.
         */
        "previewImage"?: string;
        /**
          * URL of the video to embed (YouTube, Vimeo, or any other iframe URL)
         */
        "src"?: string;
        /**
          * Title of the video (used for the iframe title, for accessibility)
         */
        "videoTitle"?: string;
        /**
          * Width of the embed (can be px or %)
         */
        "width"?: string;
        /**
          * Load YouTube videos via youtube-nocookie.com (enhanced privacy mode)
         */
        "youtubeNocookie"?: boolean;
    }
    interface IntrinsicElements {
        "lazy-embed": LazyEmbed;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lazy-embed": LocalJSX.LazyEmbed & JSXBase.HTMLAttributes<HTMLLazyEmbedElement>;
        }
    }
}
